#!/usr/bin/env bash
# Library-Class: entrypoint-helper

if [[ -n "${_SETUP_LIB_CONFIG_LOADED:-}" ]]; then
  return 0
fi
readonly _SETUP_LIB_CONFIG_LOADED=1

function exo_collect_setup_config() {
  local template_dir="${1}"
  local core_only="${2}"

  read -r -p "GitHub username (или Enter для пропуска): " GITHUB_USER
  GITHUB_USER="${GITHUB_USER:-your-username}"

  read -r -p "Имя вашего экзокортекс-репо [DS-exocortex]: " EXOCORTEX_REPO
  EXOCORTEX_REPO="${EXOCORTEX_REPO:-DS-exocortex}"

  read -r -p "Workspace directory [$(dirname "${template_dir}")]: " WORKSPACE_DIR
  WORKSPACE_DIR="${WORKSPACE_DIR:-$(dirname "${template_dir}")}"
  WORKSPACE_DIR="${WORKSPACE_DIR/#\~/${HOME}}"

  if [[ "${core_only}" == "true" ]]; then
    CLAUDE_PATH="${AI_CLI:-claude}"
    TIMEZONE_HOUR="4"
    TIMEZONE_DESC="4:00 UTC"
  else
    read -r -p "Claude CLI path [$(command -v claude || echo '/opt/homebrew/bin/claude')]: " CLAUDE_PATH
    CLAUDE_PATH="${CLAUDE_PATH:-$(command -v claude || echo '/opt/homebrew/bin/claude')}"

    read -r -p "Strategist launch hour (UTC, 0-23) [4]: " TIMEZONE_HOUR
    TIMEZONE_HOUR="${TIMEZONE_HOUR:-4}"

    read -r -p "Timezone description (e.g. '7:00 MSK') [${TIMEZONE_HOUR}:00 UTC]: " TIMEZONE_DESC
    TIMEZONE_DESC="${TIMEZONE_DESC:-${TIMEZONE_HOUR}:00 UTC}"
  fi

  HOME_DIR="${HOME}"
  CLAUDE_PROJECT_SLUG="$(printf '%s' "${WORKSPACE_DIR}" | tr '/' '-')"
}

function exo_print_setup_config() {
  local core_only="${1}"

  echo "Configuration:"
  echo "  GitHub user:    ${GITHUB_USER}"
  echo "  Exocortex repo: ${EXOCORTEX_REPO}"
  echo "  Workspace:      ${WORKSPACE_DIR}"
  if [[ "${core_only}" == "true" ]]; then
    echo "  Mode:           core (offline)"
  else
    echo "  Claude path:    ${CLAUDE_PATH}"
    echo "  Schedule hour:  ${TIMEZONE_HOUR} (UTC)"
    echo "  Time desc:      ${TIMEZONE_DESC}"
  fi
  echo "  Home dir:       ${HOME_DIR}"
  echo "  Project slug:   ${CLAUDE_PROJECT_SLUG}"
  echo ""
}

function exo_write_iwe_env() {
  local dry_run="${1}"
  local env_dir="${HOME}/.$(basename "${WORKSPACE_DIR}")"
  local env_file="${env_dir}/env"

  if [[ "${dry_run}" == "true" ]]; then
    echo "  [DRY RUN] Would write config: ${env_file}"
    return 0
  fi

  mkdir -p "${env_dir}"
  {
    echo "# IWE configuration — generated by setup.sh $(date +%Y-%m-%d)"
    echo "# Re-run setup.sh to update"
    printf 'GITHUB_USER=%q\n' "${GITHUB_USER}"
    printf 'EXOCORTEX_REPO=%q\n' "${EXOCORTEX_REPO}"
    printf 'WORKSPACE_DIR=%q\n' "${WORKSPACE_DIR}"
    printf 'CLAUDE_PATH=%q\n' "${CLAUDE_PATH}"
    printf 'TIMEZONE_HOUR=%q\n' "${TIMEZONE_HOUR}"
    printf 'TIMEZONE_DESC=%q\n' "${TIMEZONE_DESC}"
    printf 'HOME_DIR=%q\n' "${HOME}"
    printf 'CLAUDE_PROJECT_SLUG=%q\n' "${CLAUDE_PROJECT_SLUG}"
  } > "${env_file}"
  chmod 600 "${env_file}"
  echo "  Written: ${env_file}"
}
